version: 2
jobs:
  build:
    docker:
      - image: clojure:lein
    steps:
      - checkout
      - restore_cache:
          key: ring-request-proxy-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          key: ring-request-proxy-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
      - run: lein spec
      - deploy:
          name: Deploy to Clojars
          command: lein deploy clojars
    working_directory: ~/ring-request-proxy
